name: Archive Latest Stream

on:
  schedule:
    - cron: '30 2,3,4 * * 5'  # Każdy poniedziałek o 12:00 UTC
  workflow_dispatch:  # Pozwala na ręczne uruchomienie

jobs:
  archive-stream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python -m pip install --upgrade pip
        pip install yt-dlp requests
        pip install doodstream

    - name: Download stream
      run: python download_stream.py
    
    - name: Upload to DOODSTREAM
      env:
        DOODSTREAM_API_KEY: ${{ secrets.DOODSTREAM_API_KEY }}
      run: |
        for file in *.mp4; do
          if [ -f "$file" ]; then
            python upload_to_doodstream.py "$file"
            rm "$file"
          else
            echo "Nie znaleziono pliku MP4 do przesłania."
          fi
        done

    - name: Clean up
      run: |
        rm -f *.mp4
        rm -f *.part
