name: Archive Latest YouTube Stream

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  archive-stream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp requests
    
    - name: Run archiving script
      env:
        DOODSTREAM_API_KEY: ${{ secrets.DOODSTREAM_API_KEY }}
      run: python archive_stream.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Archive latest stream" -a || echo "No changes to commit"
        git push
