name: Upload Video to DoodStream

on:
  schedule:
    - cron: '0 0 * * *' # Uruchamiaj codziennie o północy (UTC)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yt-dlp requests

    - name: Run script
      env:
        DOODSTREAM_API_KEY: ${{ secrets.DOODSTREAM_API_KEY }}
      run: python script.py
