name: YouTube Archive

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at 00:00 UTC
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp youtube-dl ffmpeg
        python -m pip install --upgrade pip
        
    - name: Make ytarchive executable
      run: chmod +x ./ytarchive

    - name: Run ytarchive
      run: ./ytarchive -w https://www.youtube.com/watch?v=mYNp4nIlo_g 1080p60/best

    - name: Commit and push changes
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
